### PR TITLE
go-stream-client producer/consumer

### PR DESCRIPTION
**Pull request by ablease**
Examples for go-stream-client. 

Dependencies are provided in each app's `vendor/` directory. 

Start rabbitmq locally, and `go run producer.go` + `go run consumer.go`!

### CODE REVIEW

**Review by Zerpet — CHANGES_REQUESTED** [review]
Do we need to vendor the dependencies? Isn't it enough to have a `go.mod` and `go.sum` to build these apps?

**Review by DanielePalaia — CHANGES_REQUESTED** [review]
I think that as the framework is working we don't have to declare the stream:
We just create the stream manually and then we run all the clients. I can see that if the stream is already there this producer is failing.
The other clients send 100 simple messages, 100 messages with the message properties (message_id, correlation_id ecc), and 100 message with message + application_properties, I think we should do the same here.

**Review by lukebakken — CHANGES_REQUESTED** [review]
The go module system should be used, or git submodules for dependencies.

**Comment by Zerpet** [comment]
> We just create the stream manually and then we run all the clients.

What's the benefit of creating the streams manually? 😕 
I agree that the app should not fail if the stream already exists, just log a message and move on.

**Comment by DanielePalaia** [comment]
@Zerpet Well it was a specific request of Gabriele in the doc 4- Producer DOES NOT create the stream queue. :)
But anyway yes I agree I think the main point is not to fail on creation time of the stream and not delete the stream on consumer side in order to let all the producers/consumers to run.

**Comment by ablease** [comment]
@DanielePalaia @Gsantomaggio 

I made the changes we talked about, sending 100 of each message type.

**Review by Gsantomaggio — APPROVED** [review]

**Pull request merged**
